### ISSUE TITLE
Support postgresql-12

### ISSUE THREAD

**Issue by kenny291** [Percona-Lab/clickhousedb_fdw#25]
Do you plan to support Postgresql version 12 ?.

**Comment by nshah14285** [comment]
+1

**Comment by thebf** [comment]
Have a look at : https://github.com/adjust/clickhouse_fdw
It looks like it's actively maintained and I think it was forked from this.
Ive tested it and it seems to work better as well.

**Comment by khiem291** [comment]
@thebf, thank for your comment.
I used adjust/clickhouse_fdw with postgresql 12, query performance was not good.

**Comment by mkabilov** [comment]
@khiem291 Can you open an issue in adjust/clickhouse_fdw repo with description of your problem?
