### ISSUE TITLE
make: *** No rule to make target 'clickhousedb_fdw.o', needed by 'clickhousedb_fdw.so'.  Stop.

### ISSUE THREAD

**Issue by kolykhalov** [Percona-Lab/clickhousedb_fdw#29]
Hello!

This happens at installation. Ubuntu 20. Please advise. Thanks.

**Comment by algutorov** [comment]
me too

**Comment by dsemenischev** [comment]
CentOS 7, PG 13, the same problem.

**Comment by jovel-uc** [comment]
This happens at installation.  Ubuntu 18

**Comment by lensws** [comment]
```make: *** No rule to make target `clickhousedb_fdw.o', needed by `clickhousedb_fdw.so'.  Stop.```
Same problem
Postgres 13.3
Linux Centos 7.9.2009

**Comment by kolykhalov** [comment]
Guys looks like this FDW is dead. Shouldn't be waiting for this resolution. I managed with another FDW and it works.

**Comment by nshah14285** [comment]
Same error
>make: *** No rule to make target 'clickhousedb_fdw.o', needed by 'clickhousedb_fdw.so'.  Stop.

OS: Ubuntu 18.04
PG: 11

**Comment by kolykhalov** [comment]
Closing this issue, since authors just dropped this project. There's another fdw out there, google it and use it.
